In [6]:
pip install pandas numpy


Note: you may need to restart the kernel to use updated packages.


In [4]:
import pandas as pd
import numpy as np
import statistics

In [7]:
pip install statistics

  Created wheel for statistics: filename=statistics-1.0.3.5-py3-none-any.whl size=7454 sha256=0d0d9e85f0f76b878a44bcb3607edd54b80c88ab1f00b085df102ab1876dfb24
  Stored in directory: c:\users\abc\appdata\local\pip\cache\wheels\26\3c\70\9467407f3aa90862061eadcd286627b23a8bab6789b667776f
Successfully built statistics
Note: you may need to restart the kernel to use updated packages.


In [19]:
import pandas as pd
import numpy as np
import statistics as st

In [9]:
#number 1
a = np.array([1, 2, 3])
b= np.array([4, 5, 6])
c = a + b
print(c)

[5 7 9]


In [10]:
#number 2 - array of 10 zeros and reshape it to (2,5)
array = np.zeros(10)
print(f"the array is {array}")
reshaped_array = np.reshape(array, (2,5))
print(f"the reshaped array is {reshaped_array}")

the array is [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
the reshaped array is [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [24]:
#number 3 - mean, mode, median, standard deviation
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
print("Mean is ", np.mean(data))
print("Mode is ", st.mode(data))
print("Median is ", st.median(data))
print("Standard Deviation is ", np.std(data))

Mean is  10.5
Mode is  1
Median is  10.5
Standard Deviation is  5.766281297335398


In [26]:
#question 4 - a 6x6 numpy array with random values and find the min and max values
values = np.random.random((6, 6))
print(f"Array is {values}")
maxi = values.max()
print(f"The maximum is {maxi}")
mini = values.min()
print(f"The miniimum is {maxi}")

Array is [[0.57366262 0.83400459 0.53283201 0.2975982  0.96659285 0.03171084]
 [0.7043215  0.5147432  0.14659026 0.8576406  0.97969823 0.64368045]
 [0.98395747 0.70447789 0.99204331 0.03714088 0.35122907 0.10508385]
 [0.6751632  0.38338528 0.46574252 0.29443611 0.80770347 0.6022997 ]
 [0.51286679 0.03982793 0.45104133 0.48488816 0.29538083 0.87171014]
 [0.72937457 0.07298161 0.09233097 0.64806108 0.71950673 0.72048052]]
The maximum is 0.9920433138513735
The miniimum is 0.9920433138513735


In [32]:
#question 5 -3D numpy array and reshape it to 2d

array = np.array([[[30, 60], [70, 10]], [[30, 60], [70, 10]], [[30, 60], [70, 10]], [[30, 60], [70, 10]]])
reshaped_array = np.reshape(array, (4, 4))
print(f"The reshaped array is {reshaped_array}")

The reshaped array is [[30 60 70 10]
 [30 60 70 10]
 [30 60 70 10]
 [30 60 70 10]]


In [35]:
#number 6 -creating a 1D array
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array = np.array(data)
result = array.flatten()
print(f"The 1D array is {result}")

The 1D array is [1 2 3 4 5 6 7 8 9]
